.changeset/old-boats-dance.md
packages/react-three-rapier/src/Physics.tsx
packages/react-three-rapier/src/hooks.ts

Global colliders setting propagate to children

---

demo/src/App.tsx
demo/src/car/Car.tsx

Hope this car demo using revolute joints and apply torque can be of some use

Add a car example to demos

---

.changeset/moody-mayflies-do.md
packages/react-three-rapier/src/RigidBody.tsx

feat: allow object3d props through RigidBody

---

.changeset/nice-forks-hug.md
.changeset/red-phones-swim.md
.changeset/small-houses-change.md
.changeset/stupid-rings-live.md
demo/index.html
demo/src/App.tsx
demo/src/all-colliders/AllCollidersExample.tsx
demo/src/cradle/Cradle.tsx
packages/react-three-rapier/package.json
packages/react-three-rapier/readme.md
packages/react-three-rapier/src/Debug.tsx
packages/react-three-rapier/src/types.ts
packages/react-three-rapier/src/utils.ts
yarn.lock

- Fixes incorrect Heightfield arguments
- Fixes wrong proportions of cylinders
- Add debug shapes for all supported colliders
- Fix RoundCubeCollider

Debug collider shapes upgrades

---

.changeset/long-coats-join.md
packages/react-three-rapier/src/Physics.tsx

See https://github.com/pmndrs/react-three-rapier/issues/76

Introduce `updatePriority` prop to `<Physics>`

---

.changeset/tasty-cameras-bake.md
packages/react-three-rapier/src/Physics.tsx

fix: clamp deltatime values to 1 second.

---

.changeset/silver-dryers-joke.md
package.json
packages/react-three-rapier/readme.md
packages/react-three-rapier/src/Physics.tsx

As discussed. I've updated the README, included a changeset, and tried it in the demo.

`timeStep="vary"`

---

.changeset/early-trains-run.md
.changeset/few-moles-try.md
demo/src/App.tsx
packages/react-three-rapier/src/AnyCollider.tsx
packages/react-three-rapier/src/Physics.tsx
packages/react-three-rapier/src/utils-collider.ts

Also fix parent-less collider transforms

fix(AnyCollider): use mergedProps in AnyCollider

---

.changeset/shy-crews-care.md
packages/react-three-rapier/src/types.ts

See https://github.com/dimforge/rapier.js/blob/master/src.ts/geometry/collider.ts

Fix collider arg type hints

---

.changeset/calm-drinks-behave.md
packages/react-three-rapier/src/api.ts

Minor jsdoc fix for `setNextKinematicTranslation`

fix: jsdoc for setNextKinematicTranslation

---

packages/react-three-rapier/readme.md

A very humble first commit, details I noticed in the docs on a first read.

docs: a couple of typos in the readme

---

.changeset/sour-roses-live.md
.github/workflows/r3-rapier-docs.yml
.gitignore
demo/src/examples/collision-events/CollisionEventsExample.tsx
demo/src/examples/cradle/CradleExample.tsx
demo/src/examples/performance/PeformanceExample.tsx
package.json
packages/react-three-rapier/readme.md
packages/react-three-rapier/src/AnyCollider.tsx
packages/react-three-rapier/src/Attractor.tsx
packages/react-three-rapier/src/Debug.tsx
packages/react-three-rapier/src/InstancedRigidBodies.tsx
packages/react-three-rapier/src/MeshCollider.tsx
packages/react-three-rapier/src/Physics.tsx
packages/react-three-rapier/src/RigidBody.tsx
packages/react-three-rapier/src/api.ts
packages/react-three-rapier/src/hooks.ts
packages/react-three-rapier/src/index.ts
packages/react-three-rapier/src/joints.ts
packages/react-three-rapier/src/types.ts
packages/react-three-rapier/tsconfig.json
tsconfig.json
yarn.lock

- Clean up a lot of types
- Rename a heck ton of types in the back
- Export a lot of missing types that could be  useful

feat(docs): add some proper generated docs with Typedoc

---

packages/react-three-rapier/src/components/Attractor.tsx
packages/react-three-rapier/src/components/Physics.tsx
packages/react-three-rapier/src/types.ts

https://tsdoc.org/pages/tags/defaultvalue/

docs: standardized defaults to use @defaultValue

---

packages/react-three-rapier/src/types.ts
packages/react-three-rapier/src/utils/utils-rigidbody.ts

https://rapier.rs/docs/user_guides/javascript/rigid_bodies#dominance

feat: add dominace group to rigid body

---

.github/workflows/r3-rapier-docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
package.json
packages/react-three-rapier/src/hooks/hooks.ts
packages/react-three-rapier/test/physics.test.tsx
packages/react-three-rapier/test/test-utils.tsx
yarn.lock

Adds tests for errors, and adds a test workflow to the github actions.

test(physics): add tests for errors

---

.changeset/chatty-jobs-repair.md
packages/react-three-rapier/src/components/Physics.tsx

- 📦 Other (tests, refactoring, docs, etc.)

docs: add better docs for setWorld

---

.changeset/little-doors-doubt.md
demo/src/App.tsx
demo/src/examples/contact-skin/ContactSkinExample.tsx
packages/react-three-rapier-addons/package.json
packages/react-three-rapier/package.json
packages/react-three-rapier/src/components/Physics.tsx
packages/react-three-rapier/src/hooks/joints.ts
packages/react-three-rapier/src/types.ts
packages/react-three-rapier/src/utils/singleton-proxy.ts
packages/react-three-rapier/src/utils/utils-collider.ts
packages/react-three-rapier/src/utils/utils-rigidbody.ts
packages/react-three-rapier/src/utils/utils.ts
packages/react-three-rapier/tests/physics.test.tsx
yarn.lock

- Bump @dimforge/rapier3d-compat from 0.12.0 to 0.13.1
- Expose new features
- RigidBody `softCcdPrediction`
- Collider `contactSkin`
- World `lengthUnit`
- Addresses https://github.com/pmndrs/react-three-rapier/issues/667

feat: update to @dimforge/rapier3d-compat 0.13.1

---

packages/react-three-rapier/CHANGELOG.md

- update changelog, add link to rapier.js changelog

chore: update CHANGELOG.md

---

.github/workflows/r3-rapier-docs.yml

fix: update r3-rapier-docs.yml github action versions

---

.changeset/thirty-terms-care.md
packages/react-three-rapier/package.json
yarn.lock

- feat: bump @dimforge/rapier3d-compat from v0.14.0 to v0.15.0

feat: bump @dimforge/rapier3d-compat from v0.14.0 to v0.15.0
